# Generated by Django 3.2.20 on 2025-12-15 06:30

from django.db import migrations


def create_predefined_categories(apps, schema_editor):
    """Create predefined finance categories"""
    Category = apps.get_model('wallet', 'Category')
    categories = ['Salary', 'Business', 'Freelancing', 'Investment']
    
    for category_name in categories:
        Category.objects.get_or_create(name=category_name)


def reverse_create_categories(apps, schema_editor):
    """Remove predefined categories"""
    Category = apps.get_model('wallet', 'Category')
    categories = ['Salary', 'Business', 'Freelancing', 'Investment']
    
    Category.objects.filter(name__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_predefined_categories, reverse_create_categories),
    ]
